[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 50000
multiplier = 3

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 25
y = 15

[window.position]
x = 0
y = 0
